system:
  jwt:
    secret-key: your-long-secret-key-32bytes-min
    expiration: 7200000
  init:
    admin:
      name: Grefer
      password: 123456

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db01
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 250MB
  # RabbitMQ配置
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: Project1
    username: admin
    password: admin
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          # 开启重试
          enabled: true
          # 最大重试次数
          max-attempts: 3
          # 首次重试时间间隔
          initial-interval: 1000
          max-interval: 1000
          stateless: true


  data:
    redis:
      port: 6379
      password: hghgnzlbd
      host: localhost
      database: 0
      timeout: 60s
      lettuce:
        pool:
          enabled: true
          max-active: 44  # 允许最大连接数,默认8(负值表示没有限制),推荐值;大于cpu * 2,通常为(cpu * 2) + 2
          max-idle: 40     # 最大空闲连接数,默认8,推荐值;cpu * 2
          min-idle: 0     # 最小空闲连接数,默认0
          max-wait: 5s    # 连接用完时,新的请求等待时间(s秒、ms毫秒),超过该时间抛出异常,默认-1(负值表示没有限制)





mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.aiqa.project1.pojo
  configuration:
    map-underscore-to-camel-case: true

qclode:
  cos:
    rootSrc: "ai-docs-qa-platform-1390443137.cos.ap-beijing.myqcloud.com"
    SecretId: "AKIDNrBICsaItHSSGqDNJ3vc6NSJwQltqa7R"
    SecretKey: "AE4rStCNUipw4INEsQmuseEbljU2LROh"
    bucketName: "ai-docs-qa-platform-1390443137"
    bucketAddr: "ap-beijing"

snowflake:
  datacenterId: 1
  machineId: 1

langchain4j:
  TextConfig:
    CHUNK_SIZE: 500
    CHUNK_OVERLAP: 50
    BIG_CHUNK_SIZE: 1024
    BIG_CHUNK_OVERLAP: 128
    SMALL_CHUNK_SIZE: 256
    SMALL_CHUNK_OVERLAP: 32
#  http:
#    client:
#      builder-factory: dev.langchain4j.http.client.jdk.JdkHttpClientBuilderFactory # JDK客户端
  open-ai:
    chat-model:
          baseUrl: https://api.deepseek.com/v1
          modelName: deepseek-chat
          log-requests: true
          log-responses: true
  ollama:
    embedding-model:
          base-url: http://127.0.0.1:11434
          model-name: qwen3-embedding-0.6b-q8
          log-requests: true
          log-responses: true
  milvus:
    host: 127.0.0.1
    port: 19530
    database-name: Project1
    dimension: 1024
    collection-name: test
    index-type: FLAT # 索引类型(测试用FLAT即可)
    metric-type: COSINE # 相似度计算方式(余弦相似度)
    consistency-level: strong


milvus:
  host: 127.0.0.1
  port: 19530
  database-name: Project1
  dimension: 1024
  collection-name: test
  index-type: FLAT # 索引类型(测试用FLAT即可)
  metric-type: COSINE # 相似度计算方式(余弦相似度)
  consistency-level: strong

rag:
  sub-question:
    cache-expire-seconds: 60
    enable-cache: false
    retrieve-retry-times: 2
    retrieve-top-k: 10
    sub-question-max-num: 5
    retrieve-timeout-ms: 5000